version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\OpenFunscripter
install:
    - git submodule update --init --recursive
image:
- Visual Studio 2019
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Visual Studio 16 2019" -A x64
build:
  project: c:\projects\OpenFunscripter\build\src\OpenFunscripter.sln
  verbosity: detailed
  parallel: true