branches:
  only:
  - master
clone_folder: c:\projects\OpenFunscripter
install:
   - git submodule update --init --recursive
image:
- Visual Studio 2019
configuration:
# - Debug
- Release

platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

before_build:
- ps: choco install -y -r --no-progress InnoSetup
- ps: set PATH=%PATH%;"C:\\ProgramData\\chocolatey\\bin";"C:\\Program Files (x86)\\Inno Setup 6"
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Visual Studio 16 2019" -A x64
build:
  project: c:\projects\OpenFunscripter\build\src\OpenFunscripter.sln
  verbosity: minimal
  parallel: true

cache:
# - lib\

after_build:
- cmd: |-
    cd ..
    mkdir ffmpeg
    appveyor DownloadFile "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z" -FileName "./ffmpeg/ffmpeg-release-essentials.7z"
    cd ffmpeg
    7z e ffmpeg-release-essentials.7z
  
- ps: dir
- ps: cd ..
- ps: dir
- ps: iscc ofs-installer.iss   
- ps: Push-AppveyorArtifact installer\ofs-installer.exe -FileName OFS-$env:CONFIGURATION-$env:APPVEYOR_BUILD_VERSION.exe

# artifacts:
# - path: /bin/$(configuration)/OFS-$(platform)_$(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_REPO_COMMIT).7z