name: openfunscripter
base: core20 
version: git 
summary: openfunscripter
description: |
  A tool to create funscripts.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict #devmode # use 'strict' once you have the right plugs and slots

environment:
  LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/samba:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$LD_LIBRARY_PATH
  #  LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri

apps:
  OpenFunscripter:
    command: bin/desktop-launch $SNAP/usr/local/bin/OpenFunscripter
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - network
      - opengl
      - audio-playback
      - x11
      - gsettings
    slots:
      - mpris

parts:
  app:
    source: .
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DOFS_SNAP_IMAGE=1
    build-packages:
      - libmpv-dev
      - libglvnd-dev
      - libxext-dev
      - pkg-config
    stage-packages:
      - libmpv1
      - samba-libs
      - libglu1-mesa
      - freeglut3
      - zenity
    after:
      - desktop-helper

  desktop-helper:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
