name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
   
    - name: EASTL special treatment
      run: |
        cd lib/EASTL
        git submodule update --init
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target "OpenFunscripter"
    
    - name: FFMPEG & Zip 
      run: |
        choco install -y -r --no-progress 7zip
        choco install -y -r --no-progress InnoSetup
        powershell Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z" -OutFile "${{runner.workspace}}\ffmpeg.7z" 

        mkdir "${{runner.workspace}}\ffmpeg"
        7z e "${{runner.workspace}}\ffmpeg.7z" -o${{runner.workspace}}\ffmpeg
        cp "${{runner.workspace}}\ffmpeg\ffmpeg.exe" "${{runner.workspace}}\OFS\bin\Release\ffmpeg.exe"
        powershell Compress-Archive "${{runner.workspace}}\OFS\bin\Release" "${{runner.workspace}}\OFS-64x_${{github.sha}}.zip"
        
    - uses: actions/upload-artifact@v2
      with:
        name: OFS-64x_${{github.sha}}.zip
        path: ${{runner.workspace}}\bin\OFS-64x_${{github.sha}}.zip
      
